[build-system]
requires = ["setuptools>=68", "wheel"]

[project]
name = "circuit-tracing-llm"
version = "0.1.0"
description = "Mechanistic interpretability study of arithmetic in LLMs"
readme = "README.md"
requires-python = ">=3.10"
